[package]
name = "spacemines"
version = "0.1.0"
edition = "2021"

[dependencies]
libcosmic = { git = "https://github.com/pop-os/libcosmic"}
crossterm = "0.27.0"
backtrace = "0.3.71"
rand = { version = "0.8.5", features = ["small_rng"]}
