name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Fetching Deps
      run: cd libcosmic && git submodule init && git submodule update --init --recursive && cd .. && cargo fetch --locked
    - name: Build
      run:  cargo build --verbose --frozen
    - name: Run tests
      run: cargo test --verbose --frozen
