name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install Dependencies
      run: sudo apt update && sudo apt upgrade && sudo apt install libxkbcommon-dev
    - name: Fetching Deps
      run: cargo fetch --locked
    - name: Build
      run:  cargo build --frozen
    - name: Run tests
      run: cargo test --verbose --frozen
